title: Bhavik Rohit
logo: /images/Picsart_24-05-06_13-56-04-268.png
#description: text below image
social:
  linkedin: https://www.linkedin.com/in/bhavik-rohit/
  github: github.com/Bhavik2209
show_downloads: true
theme: jekyll-theme-minimal
